# Generated by Django 3.0.5 on 2020-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ph_no', models.IntegerField(default=0)),
                ('dob', models.DateTimeField(null=True)),
                ('msg', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
